package pokemon;

public enum Ability {

	ADAPTABILITY("Changes the STAB bonus from 1.5x to 2x."),
	AMBUSH("Gives +1 priority to the first move this Pokemon uses when it enters battle."),
	ANALYTIC("Boosts move power by 1.3x when the Pokemon moves last."),
	ANGER_POINT("Maxes highest attack after taking a critical hit."),
	ANTICIPATION("Senses the foe's supereffective moves, halving damage from the first one if it exists."),
	INSOMNIA("Prevents the Pokemon from falling asleep."),
	BATTLE_ARMOR("This Pokemon cannot be Critical hit."),
	BEAST_BOOST("Boosts the Pokemon's highest stat every time it faints a foe."),
	BERSERK("Sharply boosts the Pokemon's highest attacking stat when it falls below half HP."),
	BLACK_HOLE("Restores 1/4 of max HP if hit by a LIGHT or GALACTIC move."),
	BLAZE("Powers up FIRE moves by 20%, or 50% when at or below 1/3 of max HP."),
	BRAINWASH("Forces the opponent's stat changes to have an opposite effect while the user is active."),
	CHLOROPHYLL("Doubles the Pokemon's Speed stat in SUNSHINE."),
	CLEAR_BODY("Prevents other Pokemon from lowering its stats."),
	CLOUD_NINE("Prevents weather from getting set and clears it on switch-in."),
	COLD_HEART("Immune to all PSYCHIC moves."),
	COMPETITIVE("Boosts the Pokemon's Sp. Atk stat by 2 when its stats are lowered."),
	COMPOUND_EYES("The Pokemon's accuracy is boosted by 1.3x."),
	CONTRARY("Makes stat changes have an opposite effect."),
	CORROSION("The Pokemon can hit STEEL Pokemon with POISON moves, and can always Poison the target regardless of typing."),
	COSMIC_WARP("Twists the dimensions for 4 turns when the Pokemon enters the battle, reversing the speed order."),
	CURSED_BODY("30% chance to disable a move used on the Pokemon."),
	DEFIANT("Boosts the Pokemon's Attack stat by 2 when its stats are lowered."),
	DJINN1S_FAVOR("Raises highest attack if hit by a MAGIC move."),
	DRIZZLE("The Pokemon makes it RAIN for 5 turns when it enters a battle."),
	DRY_SKIN("Restores 1/8 HP in RAIN or 1/4 HP when hit by WATER moves, but loses 1/8 HP in SUN and is 1.25x weaker to FIRE."),
	DROUGHT("Turns the sunlight HARSH for 5 turns when it enters a battle."),
	ELECTRIC_SURGE("Turns the ground into ELECTRIC TERRAIN for 5 turns when the Pokemon enters a battle."),
	EMPATHIC_LINK("The Pokemon gets a boost in their highest attack after the foe raises any stat."),
	ENCHANTED_DUST("Changes the foe's type to MAGIC upon entry."),
	EVERGLOW("Sets up Aurora Glow for 5 turns when the Pokemon enters battle, healing all ally LIGHT, ICE and GALACTIC types."),
	ILLUMINATION("Grants the user all the resistances from the LIGHT type."),
	FILTER("Halves damage from supereffective attacks."),
	FLAME_BODY("Contact with the Pokemon can cause a burn 30% of the time."),
	FLASH_FIRE("It powers up FIRE moves by 1.5x if it's hit by one."),
	FLUFFY("Halves the damage from moves that make direct contact, but doubles that of FIRE moves."),
	FORTIFY("If this Pokemon doesn't take direct damage for the turn and doesn't protect itself, it gains +1 Defense (max 2 stacks)."),
	FRIENDLY_GHOST("Gives full immunity to all GHOST moves."),
	FULL_FORCE("Boosts the Attack stat by 2 stages if the Pokemon's held item is used or lost."),
	GALACTIC_AURA("Halves the damage of ICE and PSYCHIC moves."),
	GALVANIZE("NORMAL moves become ELECTRIC moves. The power of those moves is boosted by 1.2x."),
	GLACIER_AURA("Weakens the power of Physical moves."),
	GLASS_GUARD("When hit by a supereffective attack, the Pokemon creates a Magic Reflect for itself."),
	GOOEY("Contact with the Pokemon lowers the attacker's Speed stat."),
	GRASSY_SURGE("Turns the ground into GRASSY TERRAIN for 5 turns when the Pokemon enters a battle."),
	GRAVITATION("Creates GRAVITY for 5 turns when the Pokemon enters a battle."),
	GUTS("Boosts the Attack stat by 1.5x if the Pokemon has a status condition."),
	HEAT_COMPACTION("Raises Defense and Sp. Def if hit by an FIRE move."),
	HUGE_POWER("Doubles the Pokemon's Attack stat."),
	HYDRATION("Cures the Pokemon's status conditions in RAIN at the end of each turn."),
	HYPER_CUTTER("Prevents other Pokemon from lowering this Pokemon's Attack stat."),
	ICE_BODY("The Pokemon regains 1/8 max HP in SNOW."),
	ICY_SCALES("Halves the damage from special moves."),
	ILLUSION("Entering battle will boost damage by 1.2x and prevents foes from escaping until hit."),
	INNER_FOCUS("The Pokemon is protected from flinching; ignores switch-in stat-lowering Abilities."),
	INSECT_FEEDER("Restores 1/4 max HP if hit by a BUG move."),
	INTIMIDATE("Lowers the opposing Pokemon's Attack stat."),
	IRON_BARBS("Inflicts 1/8 max HP damage to the Pokemon on contact."),
	IRON_FIST("Boosts the power of punching moves by 1.3x."),
	JACKPOT("Rolls a dice with each attack corresponding to its power: 50% - 200% (Loaded Dice = 100% - 200%)."),
	JUSTIFIED("Halves damage from DARK moves and sharply boosts Attack when hit by one."),
	KEEN_EYE("Prevents the Pokemon from losing accuracy."),
	LEVITATE("Gives full immunity to all GROUND moves."),
	LIGHTNING_ROD("Raises highest attack if hit by an ELECTRIC move."),
	MAGIC_BOUNCE("Reflects status moves that target this Pokemon/Pokemon's side instead of getting hit by them."),
	MAGIC_GUARD("The Pokemon only takes damage from attacks."),
	MAGICAL("Powers up MAGIC moves by 1.5x."),
	MAGMA_ARMOR("This Pokemon can't be Critical hit, and prevents the Pokemon from getting a frostbite."),
	MERCILESS("The Pokemon's attacks become critical hits if the target is poisoned, badly poisoned or paralyzed."),
	MIRROR_ARMOR("Bounces back only the stat-lowering effects that the Pokemon receives."),
	MOLD_BREAKER("Ignores the foe's ability when attacking."),
	MOODY("Raises one stat sharply and lowers another every turn."),
	MOSAIC_WINGS("Distorts type matchups to make non-super effective attacks resisted."),
	MOTOR_DRIVE("Raises Speed if hit by an ELECTRIC move."),
	MOUTHWATER("Taunts the foe on switch-in for 4 turns."),
	MOXIE("Boosts highest attack after knocking out any Pokemon."),
	MULTISCALE("Halves damage the Pokemon takes when its HP is full."),
	MYSTIC_ABSORB("Restores 1/4 max HP if hit by a MAGIC move."),
	MYSTIC_RIFT("Creates a bizzare room for 5 turns when the Pokemon enters the battle, removing the effects of items."),
	NATURAL_CURE("All status conditions heal when the Pokemon switches out."),
	NEUTRALIZING_GAS("While the Pokemon is active, the effects of all abilities will be nullified."),
	NO_GUARD("Ensures the Pokemon and its foe's attacks land."),
	NORMALIZE("All the Pokemon's moves become Normal type. The power of their moves are boosted by 1.2x."),
	OVERGROW("Powers up GRASS moves by 20%, or 50% when at or below 1/3 of max HP."),
	PARASOCIAL("The Pokemon steals 1/8 HP from an opposing confused, abducted, or asleep Pokemon."),
	PERISH_BODY("When hit by a contact move, the Pokemon and the attacker will faint after three turns."),
	PICKPOCKET("Steals an item from the foe on switch-in if this Pokemon is not holding an item."),
	PIXILATE("NORMAL moves become LIGHT moves. The power of those moves is boosted by 1.2x."),
	POISON_HEAL("Restores 1/8 max HP if the Pokemon is poisoned instead of losing HP."),
	POISON_POINT("Contact with the Pokemon can cause a poison 30% of the time."),
	POISON_TOUCH("May poison a target 30% of the time when the Pokemon makes contact."),
	PRANKSTER("Gives +1 priority to a status move."),
	PRESSURE("The Pokemon doubles the foe's PP usage."),
	PROTEAN("Changes the Pokemon's type to the move type it's about to use."),
	PSYCHIC_AURA("Weakens the power of Special moves."),
	PSYCHIC_SURGE("Turns the ground into PSYCHIC TERRAIN for 5 turns when the Pokemon enters a battle."),
	RADIANT("Lowers foe's Accuracy when this Pokemon hits with a LIGHT move."),
	RAIN_DISH("The Pokemon regains 1/8 max HP in RAIN."),
	RATTLED("Getting hit by DARK, GHOST, or BUG moves boost its Speed stat."),
	RECKLESS("Powers up moves that have recoil damage by 1.3x."),
	REFORGE("Restores 1/16 HP at the end of each turn."),
	REGENERATOR("Restores 1/3 max HP when withdrawn from battle."),
	REFRIGERATE("NORMAL moves become ICE moves. The power of those moves is boosted by 1.2x."),
	ROCK_HEAD("Prevents recoil damage."),
	ROUGH_SKIN("Inflicts 1/8 max HP damage to the Pokemon on contact."),
	SAND_FORCE("Boosts the power of moves in a SANDSTORM by 1.3x."),
	SAND_RUSH("Doubles the Pokemon's Speed stat in a SANDSTORM."),
	SAND_STREAM("The Pokemon summons a SANDSTORM for 5 turns when it enters a battle."),
	SAND_VEIL("Opposing moves are 0.8x accurate while SANDSTORM is active."),
	SAP_SIPPER("Raises highest attack if hit by an GRASS move."),
	SEABED_SIFTER("Clears any terrain on entry, and if a terrain was cleared, restores HP to full."),
	SERENE_GRACE("Doubles the chance of secondary effects occurring when attacking."),
	SCALY_SKIN("Lowers the foe's Attack, and this Pokemon only takes damage from attacks."),
	SCRAPPY("The Pokemon can hit GHOST Pokemon with NORMAL and FIGHTING moves; ignores switch-in stat-lowering Abilities."),
	SHADOW_TAG("Prevents the opposing Pokemon from escaping."),
	SHADOW_VEIL("The Pokemon is protected from an attack once per battle, at the cost of 1/8 max HP."),
	SHARP_TAIL("Boosts the power of Tail-using moves by 1.5x."),
	SHARPNESS("Boosts the power of Slicing moves by 1.5x."),
	SHED_SKIN("The Pokemon may heal its own status conditions 33% of the time at the end of each turn."),
	SHEER_FORCE("Removes secondary effects to increase the power of moves by 1.3x when attacking, ignores Life Orb recoil."),
	SHELL_ARMOR("This Pokemon cannot be Critical hit."),
	SHIELD_DUST("Blocks the secondary effects of attacks taken and is immune to entry hazards."),
	SIMPLE("The stat changes the Pokemon receives are doubled."),
	SKILL_LINK("Makes multi-hit moves always hit the maximum amount."),
	SLEIGHT_OF_HAND("Gives +1 priority to MAGIC moves when at full HP."),
	SLIPSTREAM("Switches the Pokemon out when its HP becomes half or less."),
	SLUSH_RUSH("Doubles the Pokemon's Speed stat in SNOW."),
	SNIPER("Powers up moves by 1.5x if they become critical hits."),
	SNOW_CLOAK("Opposing moves are 0.8x accurate while SNOW is active."),
	SNOW_WARNING("The Pokemon makes it SNOW for 5 turns when it enters a battle."),
	SOLAR_POWER("Boosts the Sp. Atk stat in SUNNY weather by 1.5x, but loses 1/8 max HP each turn."),
	SOLID_ROCK("Halves damage from supereffective attacks."),
	SPARKLY_SURGE("Turns the ground into SPARKLY TERRAIN for 5 turns when the Pokemon enters a battle."),
	SPEED_BOOST("Its Speed stat is boosted at the end of every active turn."),
	STARBORN("Raises highest attack by 1 if Aurora Glow is active."),
	STATIC("Contact with the Pokemon can cause a paralysis 30% of the time."),
	STEELWORKER("Powers up STEEL moves by 1.5x."),
	STICKY_HOLD("Protects the Pokemon from item theft."),
	STRONG_JAW("Boosts the power of its biting moves by 1.5x."),
	STURDY("It cannot be knocked out from full HP. One-hit KO moves cannot knock it out, either."),
	SUPER_LUCK("Heightens the critical-hit ratios of moves from 1/20 to 1/8."),
	SWARM("Powers up BUG moves by 20%, or 50% when at or below 1/3 of max HP."),
	SWIFT_SWIM("Boosts the Pokemon's Speed stat in RAIN."),
	SYNCHRONIZE("Passes a status condition or confusion to the foe when inflicted on it."),
	TALENTED("When the Pokemon enters a battle, it copies the foe's stat boosts."),
	TECHNICIAN("Powers up the Pokemon's moves 60 BP or lower by 1.5x."),
	TERRAFORGE("Raises all stats by 1 in any terrain, wears off once the terrain ends."),
	TERRIFY("Lowers the opposing Pokemon's Sp. Atk stat."),
	THICK_FAT("halves damage from FIRE and ICE moves."),
	THREATENING("Lowers the opposing Pokemon's Defense stat."),
	TINTED_LENS("Powers up \"not very effective\" moves by 2x."),
	TORRENT("Powers up WATER moves by 20%, or 50% when at or below 1/3 of max HP."),
	TOUGH_CLAWS("Powers up moves that make direct contact by 1.3x."),
	TOXIC_DEBRIS("Puts toxic spikes on the opposing side when hit by physical moves."),
	TRACE("The Pokemon copies the foe's Ability."),
	TYPE_MASTER("Grants STAB on all moves."),
	UNAWARE("Ignores the opposing Pokemon's stat changes."),
	UNBURDEN("Doubles the Speed stat if the Pokemon's held item is used or lost."),
	UNERODIBLE("Reduces damage from GRASS, WATER, and GROUND attacks by 0.25x."),
	UNWAVERING("Halves damage from DARK and GHOST moves; ignores switch-in stat-lowering Abilities."),
	VOLT_ABSORB("Restores 1/4 of max HP if hit by a ELECTRIC move."),
	VOLT_VORTEX("Doubles the Pokemon's speed in ELECTRIC TERRAIN."),
	WARM_HEART("Immune to all ICE moves."),
	WATER_ABSORB("Restores 1/4 of max HP if hit by a WATER move."),
	WATER_VEIL("Prevents the Pokemon from getting a burn."),
	WEAK_ARMOR("Physical attacks to the Pokemon lower its Defense stat but sharply raise its Speed stat."),
	WHITE_HOLE("Immune to all DRAGON moves."),
	WONDER_GUARD("Only supereffective moves will hit."),
	WONDER_SKIN("The Pokemon has full immunity to other Pokemon's status moves."),
	NULL("No Ability."),
	;

	Ability(String string) {
		desc = string;
	}
	
	@Override
	public String toString() {
		String name = super.toString();
	    name = name.toLowerCase().replace('_', ' ');
	    name = name.replace('1', '\'');
	    String[] words = name.split(" ");
	    StringBuilder sb = new StringBuilder();
	    for (String word : words) {
	        sb.append(Character.toUpperCase(word.charAt(0))).append(word.substring(1)).append(" ");
	    }
	    return sb.toString().trim();
	}
	
	public static Ability getEnum(String string) {
		// Normalize the string
	    String normalized = string.toUpperCase().replace(' ', '_');
	    normalized = normalized.replace('\'', '1');
	    
	    try {
	        return Ability.valueOf(normalized);
	    } catch (IllegalArgumentException e) {
	        throw new IllegalStateException("No matching Move enum found for string: " + string, e);
	    }
	}
	
	public String desc;

	public String superToString() {
		return super.toString();
	}
}
